<a href="https://colab.research.google.com/github/pahujam/coding-interview-notes/blob/main/ds-algo/concepts.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

- Numpy arrays are **homogeneous multidimensional** arrays ie. all of same type and have n>=2 dimensions
- Numpy = Numerical Python is an open source library
- Numpy arrays are called ndarray

In [ ]:
import numpy as np

- Create numpy 1d-array from list

In [ ]:
np.array([1,2,3])

array([1, 2, 3])

- Create 2d-array from list of list

In [ ]:
np.array([[1,2,3],[5,1,3]])

array([[1, 2, 3],
       [5, 1, 3]])

- Numpy vs Python List
- Numpy = homogenous. ie. same data type
- Python List = heterogenous, general purpose

Properties of Numpy Array:
- All elements of same type
- Once created, size cant change
- Must be rectangular. ie. each row of 2d array must have same number of cols

- Access any element by index

In [ ]:
a = np.array([1,2,3,4,5,6])

In [ ]:
a[0]

np.int64(1)

- Slice indexing
- Slicing in array creates a **view** ie. it refers to the original data.
- Slicing in list creates a copy

In [ ]:
a[1:3]

array([2, 3])

In [ ]:
a = [1,2,3]

- Create 2d array using list of lists

In [ ]:
list_of_list = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
list_of_list

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

- Indexing in list can be done in recursive manner

In [ ]:
list_of_list[2][1]

10

In [ ]:
a = np.array(list_of_list)

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- Indexing in array can be done using index only or like list

In [ ]:
a[0,1]

np.int64(2)

In [ ]:
a[0][1]

np.int64(2)

- Array Attributes
- Total Dimensions/Axis of Array
- Shape of Array

In [ ]:
a.ndim

2

In [ ]:
a.shape

(3, 4)

In [ ]:
len(a.shape)==a.ndim

True

- Total elements stored in array

In [ ]:
a.size

12

- Print type of each element (homogeneous)

In [ ]:
a.dtype

dtype('int64')

- Create Basic Arrays

In [ ]:
np.zeros(2)

array([0., 0.])

In [ ]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.ones(4)

array([1., 1., 1., 1.])

- Uninitialized Array

In [ ]:
np.empty(5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

- Create array with range of elements
- Can specify start, end and step size

In [ ]:
np.arange(4)

array([0, 1, 2, 3])

In [ ]:
np.array(range(4))

array([0, 1, 2, 3])

In [ ]:
np.arange(4,10,2)

array([4, 6, 8])

In [ ]:
np.array(range(4,10,2))

array([4, 6, 8])

- Create array with values spaced linearly over interval

In [ ]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

- Specify dtype of nd array
- Default is float64
- Int Types: int8 / int16 / int32 and so on..

In [ ]:
np.zeros((3,4),dtype=np.int32)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

- Sort Array

In [ ]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [ ]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

- Concatenate Array

In [ ]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [ ]:
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.concat((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

In [ ]:
x

array([[1, 2],
       [3, 4]])

In [ ]:
y

array([[5, 6]])

In [ ]:
concatenated_arr = np.concat((x,y))

In [ ]:
concatenated_arr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
concatenated_arr.shape

(3, 2)

- Concatenation was along axis=0 ie axis=0 was extended

In [ ]:
np.concat((x,y),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

- Concatenation along axis=1 can also be done

In [ ]:
x = np.array([[1, 2], [3, 4]])
x

array([[1, 2],
       [3, 4]])

In [ ]:
x.shape

(2, 2)

In [ ]:
y = np.array([[5], [6]])
y

array([[5],
       [6]])

In [ ]:
y.shape

(2, 1)

In [ ]:
concatenated_arr = np.concat((x,y),axis=1)
concatenated_arr

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
concatenated_arr.shape

(2, 3)

- Size/Shape/Dim of Array

In [ ]:
array_example = np.array(
[[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0, 1, 2, 3],
[4, 5, 6, 7]],
[[0 ,1 ,2, 3],
[4, 5, 6, 7]]])

In [ ]:
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [ ]:
array_example.ndim

3

In [ ]:
array_example.shape

(3, 2, 4)

In [ ]:
array_example.size

24

- Reshape an array
- Size (ie. the number of elements) must remain same
- Elements are distributed right-index to left-index

In [ ]:
a = np.arange(6)

In [ ]:
a

array([0, 1, 2, 3, 4, 5])

In [ ]:
a.reshape((2,3))

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
a.reshape((3,2))

array([[0, 1],
       [2, 3],
       [4, 5]])

- Convert 1d array to 2d (Add an axis)
- Row Vector: (1,b)
- Column Vector: (a,1)
- Matrix: (a,b)

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a.shape

(6,)

In [ ]:
a.ndim

1

In [ ]:
a2 = a[np.newaxis,:]

In [ ]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
a2.shape

(1, 6)

In [ ]:
row_vector = a[np.newaxis,:]

In [ ]:
row_vector

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
row_vector.shape

(1, 6)

In [ ]:
col_vector = a[:,np.newaxis]

In [ ]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
col_vector.shape

(6, 1)

- Expand the dimension at a specified position

In [ ]:
a = np.array(range(1,7))

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = np.expand_dims(a,axis=1)

In [ ]:
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [ ]:
b.shape

(6, 1)

In [ ]:
c = np.expand_dims(a,axis=0)

In [ ]:
c

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
c.shape

(1, 6)

- Indexing/Slicing Numpy Array

In [ ]:
data = np.array([1,2,3])

In [ ]:
data[0]

np.int64(1)

In [ ]:
data[0:2]

array([1, 2])

In [ ]:
data[-2:]

array([2, 3])

- Boolean Indexing

In [ ]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a.shape

(3, 4)

In [ ]:
mask = a<7
mask

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [ ]:
a[mask]

array([1, 2, 3, 4, 5, 6])

In [ ]:
divisible_by_2_mask = a%2==0

In [ ]:
divisible_by_2_mask

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [ ]:
a[divisible_by_2_mask]

array([ 2,  4,  6,  8, 10, 12])

- Specify multiple conditions using & and | operators

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a[(a>2) & (a<11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

- use **np.nonzero** to get indices of non zero elements
- returns tuple: (row_indices,column_indices)
- need to zip to get element indices

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b = np.nonzero((a>5)|(a<2))

In [ ]:
list_of_coordinates = list(zip(b[0],b[1]))

In [ ]:
list_of_coordinates

[(np.int64(0), np.int64(0)),
 (np.int64(1), np.int64(1)),
 (np.int64(1), np.int64(2)),
 (np.int64(1), np.int64(3)),
 (np.int64(2), np.int64(0)),
 (np.int64(2), np.int64(1)),
 (np.int64(2), np.int64(2)),
 (np.int64(2), np.int64(3))]

In [ ]:
for cord in list_of_coordinates:
    print(a[cord])

1
6
7
8
9
10
11
12

- Slicing an array
- Upating a slice of array updates the original array

In [ ]:
a = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr1 = a[3:8]

In [ ]:
arr1

array([4, 5, 6, 7, 8])

In [ ]:
arr1[1] = -1

In [ ]:
arr1

array([ 4, -1,  6,  7,  8])

In [ ]:
a

array([ 1,  2,  3,  4, -1,  6,  7,  8,  9, 10])

- Stack arrays vertically and horizontally

In [ ]:
a1 = np.array([[1, 1],
               [2,2]])

a2 = np.array([[3, 3],
               [4, 4]])

In [ ]:
a1

array([[1, 1],
       [2, 2]])

In [ ]:
a2

array([[3, 3],
       [4, 4]])

In [ ]:
np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [ ]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

- Split array horizontally
- Provide number of sections to produce

In [ ]:
x = np.arange(1, 25).reshape(2, 12)

In [ ]:
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [ ]:
np.hsplit(x,3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

- Numpy functions and operations like indexing/slicing return views (shallow copies) whenever possible for faster ops and saving memory
- Thus, modifying data in view modifies the original array!

In [ ]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b1 = a[0, :]

In [ ]:
b1

array([1, 2, 3, 4])

In [ ]:
b1[0] = 99

In [ ]:
b1

array([99,  2,  3,  4])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- Use copy to create a **deep** copy of array

In [ ]:
b2 = a.copy()

In [ ]:
b2

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
b2[0,0] = 999

In [ ]:
b2

array([[999,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [ ]:
a

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- You can add arrays with a plus sign
- It performs elem-wise addition

In [ ]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

In [ ]:
data

array([1, 2])

In [ ]:
ones

array([1, 1])

In [ ]:
data + ones

array([2, 3])

- You can also do more elem wise operations

In [ ]:
data - ones

array([0, 1])

In [ ]:
data * ones

array([1, 2])

In [ ]:
data / ones

array([1., 2.])

In [ ]:
data // ones

array([1, 2])

In [ ]:
data1 = data + ones
data1

array([2, 3])

In [ ]:
data1 += ones

In [ ]:
data1

array([3, 4])

- Sum of elements

In [ ]:
a = np.array([1, 2, 3, 4])

In [ ]:
a

array([1, 2, 3, 4])

In [ ]:
a.sum()

np.int64(10)

- Sum over a particular axis

In [ ]:
b = np.array([[1, 1], [2, 2]])

In [ ]:
b

array([[1, 1],
       [2, 2]])

In [ ]:
b.sum()

np.int64(6)

In [ ]:
b.sum(axis=0)

array([3, 3])

In [ ]:
b.sum(axis=1)

array([2, 4])

- Broadcasting = Operation b/w array and a scalar

In [ ]:
data = np.array([1.0, 2.0])

In [ ]:
data

array([1., 2.])

In [ ]:
data*1.6

array([1.6, 3.2])

- Aggregation Functions in Numpy

In [ ]:
data = np.array([1.0, 2.0])

In [ ]:
data.sum()

np.float64(3.0)

In [ ]:
data.min()

np.float64(1.0)

In [ ]:
data.max()

np.float64(2.0)

In [ ]:
data.argmax()

np.int64(1)

In [ ]:
data.argmin()

np.int64(0)

In [ ]:
data.mean()

np.float64(1.5)

In [ ]:
data.std()

np.float64(0.5)

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
a

array([[0.45053314, 0.17296777, 0.34376245, 0.5510652 ],
       [0.54627315, 0.05093587, 0.40067661, 0.55645993],
       [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
a.shape

(3, 4)

In [ ]:
a.sum()

np.float64(4.8595784)

In [ ]:
a.sum(axis=0)

array([1.12378257, 1.04875507, 1.01034462, 1.67669614])

In [ ]:
a.sum(axis=1)

array([1.51832856, 1.55434556, 1.78690428])

- Creating Matrices Using List of List

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

- Arithmetic Operations on Matrix of Same Size

In [ ]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])

In [ ]:
data

array([[1, 2],
       [3, 4]])

In [ ]:
ones

array([[1, 1],
       [1, 1]])

In [ ]:
data + ones

array([[2, 3],
       [4, 5]])

In [ ]:
data - ones

array([[0, 1],
       [2, 3]])

In [ ]:
data * ones

array([[1, 2],
       [3, 4]])

- Broadcasting a row or column vector on numpy array

In [ ]:
data = np.array([[1, 2], [3, 4], [5, 6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.shape

(3, 2)

In [ ]:
ones_row = np.array([[1, 1]])

In [ ]:
ones_row

array([[1, 1]])

In [ ]:
ones_row.shape

(1, 2)

In [ ]:
new_data = data + ones_row

In [ ]:
new_data

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
new_data.shape

(3, 2)

In [ ]:
ones_col = np.array([[1],[1],[1]])

In [ ]:
ones_col

array([[1],
       [1],
       [1]])

In [ ]:
ones_col.shape

(3, 1)

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
new_data = data + ones_col

In [ ]:
new_data

array([[2, 3],
       [4, 5],
       [6, 7]])

In [ ]:
new_data.shape

(3, 2)

- Random Number Generation in Numpy
- Random Numbers b/w [0,1]
- Random Integers Generation

In [ ]:
rand_array = np.random.random((3,4))

In [ ]:
rand_array

array([[0.31602888, 0.43608895, 0.17432734, 0.341389  ],
       [0.03308152, 0.14098848, 0.63955749, 0.18945391],
       [0.09841375, 0.0979376 , 0.04502846, 0.56011517]])

In [ ]:
rand_int_array = np.random.randint(4,size=(3,4))

In [ ]:
rand_int_array

array([[3, 0, 2, 3],
       [1, 1, 0, 3],
       [2, 0, 2, 1]])

In [ ]:
rand_int_array.shape

(3, 4)

- Get Unique Elements in Array
- Freq Count of Unique Elements
- Indices of Unique Elements

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
a

array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
a.shape

(15,)

In [ ]:
np.unique(a)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
unique_values, unique_indices = np.unique(a,return_index=True)

In [ ]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
unique_indices

array([ 0,  2,  3,  4,  5,  6,  7, 12, 13, 14])

In [ ]:
unique_values, freq_counts = np.unique(a,return_counts=True)

In [ ]:
unique_values

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
freq_counts

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1])

- Unique values and indices on 2d array
- Array is flattened here

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 3, 7, 2], [9, 10, 11, 12], [1, 2, 3, 4]])

In [ ]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  3,  7,  2],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
a_2d.shape

(4, 4)

In [ ]:
uniq_vals, uniq_indices, freq_counts = np.unique(a_2d,return_index=True,return_counts=True)

In [ ]:
uniq_vals

array([ 1,  2,  3,  4,  5,  7,  9, 10, 11, 12])

In [ ]:
uniq_indices

array([ 0,  1,  2,  3,  4,  6,  8,  9, 10, 11])

In [ ]:
freq_counts

array([2, 3, 3, 2, 1, 1, 1, 1, 1, 1])

- Unique rows in the matrix

In [ ]:
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  3,  7,  2],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
uniq_rows, uniq_row_indices, freq_counts_of_rows = np.unique(a_2d,
                                                 axis=0,
                                                 return_index=True,
                                                 return_counts=True)

In [ ]:
uniq_rows

array([[ 1,  2,  3,  4],
       [ 5,  3,  7,  2],
       [ 9, 10, 11, 12]])

In [ ]:
uniq_row_indices

array([0, 1, 2])

In [ ]:
freq_counts_of_rows

array([2, 1, 1])

- Reshaping A Matrix
- In Reshape, Looping is done starting from the last index upto the first index
- For Array, last index = column and first index = row

In [ ]:
data = np.array([[1,2],[3,4],[5,6]])

In [ ]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
data.shape

(3, 2)

In [ ]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
data.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

- Transpose of Matrix

In [ ]:
arr = np.arange(6).reshape((2, 3))

In [ ]:
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [ ]:
arr.T

array([[0, 3],
       [1, 4],
       [2, 5]])

- Reverse an Array

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
np.flip(arr)

array([8, 7, 6, 5, 4, 3, 2, 1])

- Reversing a 2d array
- This reverses along all dimensions

In [ ]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
np.flip(arr_2d)

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

- Reverse along one axis
- We can reverse only rows/cols

In [ ]:
reversed_arr_rows = np.flip(arr_2d, axis=0)

In [ ]:
reversed_arr_rows

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [ ]:
reversed_arr_cols = np.flip(arr_2d, axis=1)

In [ ]:
reversed_arr_cols

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

- Flatten an Array
- flatten -> creates a copy
- ravel -> creates a view
- ravel is memory efficient but modification in flattened array results in modification of original array

In [ ]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [ ]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
flattened_array = x.flatten()

In [ ]:
flattened_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
flattened_array[0] = 99

In [ ]:
flattened_array

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a2 = x.ravel()

In [ ]:
a2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
a2[0] = 99

In [ ]:
a2

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
x

array([[99,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- Save and Load Numpy Arrays
- Save = saves numpy array as a binary object on desk (file extension: npy)
- Load = loads numpy array from binary file (file extension: npy)
- npy format is faster and smaller!
- npy format retains dtype information

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [ ]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
np.save("filename",a)

In [ ]:
a_from_disk = np.load("filename.npy")

In [ ]:
a_from_disk

array([1, 2, 3, 4, 5, 6])

In [ ]:
a_from_disk.dtype

dtype('int64')

- Save numpy array in human-readable text formats (csv/txt)
- But it **loses** dtype information!

In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8],dtype=np.int32)

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8], dtype=int32)

In [ ]:
np.savetxt('new_file.txt', arr)

In [ ]:
arr_from_disk = np.loadtxt("new_file.txt")

In [ ]:
arr_from_disk

array([1., 2., 3., 4., 5., 6., 7., 8.])

In [ ]:
arr_from_disk.dtype

dtype('float64')

- Numpy array to csv files
- Use pandas dataframes!

In [ ]:
a = np.array([[-2.58289208,  0.43014843, -1.24082018, 1.59572603],
              [ 0.99027828, 1.17150989,  0.94125714, -0.14692469],
              [ 0.76989341,  0.81299683, -0.95068423, 0.11769564],
              [ 0.20484034,  0.34784527,  1.96979195, 0.51992837]],dtype="float32")

In [ ]:
a

array([[-2.5828922 ,  0.43014842, -1.2408202 ,  1.595726  ],
       [ 0.9902783 ,  1.1715099 ,  0.9412571 , -0.14692469],
       [ 0.7698934 ,  0.8129968 , -0.95068425,  0.11769564],
       [ 0.20484035,  0.34784526,  1.969792  ,  0.5199284 ]],
      dtype=float32)

In [ ]:
a.shape

(4, 4)

In [ ]:
import pandas as pd
df = pd.DataFrame(a)

In [ ]:
df

          0         1         2         3
0 -2.582892  0.430148 -1.240820  1.595726
1  0.990278  1.171510  0.941257 -0.146925
2  0.769893  0.812997 -0.950684  0.117696
3  0.204840  0.347845  1.969792  0.519928

In [ ]:
df.dtypes

0    float32
1    float32
2    float32
3    float32
dtype: object

In [ ]:
df.to_csv("np.csv")

- Matrix Multiplication
- \* = Element wise Multiplication
- @ = Matrix Multiply
- dot = matrix multiply

In [ ]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [ ]:
a.shape

(2, 2)

In [ ]:
b = np.array([[2,2],[1,1]])
b

array([[2, 2],
       [1, 1]])

In [ ]:
a*b

array([[2, 4],
       [3, 4]])

In [ ]:
a@b

array([[ 4,  4],
       [10, 10]])

In [ ]:
a.dot(b)

array([[ 4,  4],
       [10, 10]])

Extra Notes:
- np.random.rand vs np.random.randn = rand is uniform dist [0,1) , randn is std normal dist
- \* vs @ = \* is elem wise multiply, @ is matrix multiply

- Statistical Operations

In [ ]:
a = np.array([1,2,3,100])

In [ ]:
np.median(a)

np.float64(2.5)

In [ ]:
np.mean(a)

np.float64(26.5)

In [ ]:
np.percentile(a,50)

np.float64(2.5)

In [ ]:
np.percentile(a,25)

np.float64(1.75)

In [ ]:
np.var(a)

np.float64(1801.25)

In [ ]:
np.std(a)

np.float64(42.44113570582201)

- Vectorization in numpy array
- Vectorization refers to doing operations without using for loops
- For example, squaring each element in np array
- Vectorization is more optimized and faster because:
    - Parallelization
    - Use of C rather than Python looping mechanism
    - and many more.. (out of scope)

In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
arr**2

array([ 1,  4,  9, 16, 25])

In [ ]:
arr1 = arr.copy()
arr2 = (arr**2).copy()

In [ ]:
# adding elements one by one = slow
result = []
for i in range(len(arr1)):
    result.append(arr1[i] + arr2[i])

In [ ]:
np.array(result)

array([ 2,  6, 12, 20, 30])

In [ ]:
# using numpy array vectorized operation = faster
arr1 + arr2

array([ 2,  6, 12, 20, 30])

Linear Algbera in Numpy:
- np.dot() or np.matmul() or @ = matrix multiplication
- np.transpose() or .T = matrix transpose
- np.linalg.inv() = get inverse of matrix
- np.linalg.det() = get determinant of matrix
- np.linalg.eig() = get eigenvalues and eigenvectors of matrix
- np.linalg.svd() = compute SVD factorization

In [ ]:
A = np.array([[1, 2], [3, 4]])
A_inv = np.linalg.inv(A)
print(A_inv)

[[-2.   1. ]
 [ 1.5 -0.5]]

In [ ]:
A = np.array([[1, 2], [3, 4]])
det_A = np.linalg.det(A)
print(round(det_A,2))

-2.0

In [ ]:
A = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]

In [ ]:
a = np.array([[1, 2], [3, 4]])
U,S,Vt = np.linalg.svd(a)
print("U:\n", U)
print("S:\n", S)
print("Vt:\n", Vt)

U:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
S:
 [5.4649857  0.36596619]
Vt:
 [[-0.57604844 -0.81741556]
 [ 0.81741556 -0.57604844]]

- Cast Array to another type

In [ ]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr_casted = np.astype(arr, np.float64)

In [ ]:
arr_casted

array([1., 2., 3.])

In [ ]:
arr_casted.dtype

dtype('float64')

- Null values handling in numpy

In [ ]:
arr = np.array([1, 2, np.nan, 4],dtype=np.float32)
arr

array([ 1.,  2., nan,  4.], dtype=float32)

In [ ]:
arr.dtype

dtype('float32')

In [ ]:
np.isnan(arr)

array([False, False,  True, False])

- Fill null values with a number

In [ ]:
np.nan_to_num(arr,nan=99)

array([ 1.,  2., 99.,  4.], dtype=float32)

In [ ]:
np.nan_to_num(arr,nan=99).astype(np.int8)

array([ 1,  2, 99,  4], dtype=int8)

- Find mean ignoring null value

In [ ]:
np.nanmean(arr)

np.float32(2.3333333)